version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Users.API/Dockerfile
    depends_on:
      - nosqldata

  nosqldata:
    image: mongo
